// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqAhD8l7OBt4IS0k5piZaFbFKi6XZggmc',
    appId: '1:610035185602:web:91eea26490ebc6095ac85b',
    messagingSenderId: '610035185602',
    projectId: 'yammies-food-app',
    authDomain: 'yammies-food-app.firebaseapp.com',
    storageBucket: 'yammies-food-app.firebasestorage.app',
    measurementId: 'G-Z7YPHZX4JT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF-f5taGkV3tlZSgk5GK9M4h1VIMqu4rM',
    appId: '1:610035185602:android:e733d224555d3f585ac85b',
    messagingSenderId: '610035185602',
    projectId: 'yammies-food-app',
    storageBucket: 'yammies-food-app.firebasestorage.app',
    databaseURL: 'https://yummies-food-app-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9tKQfSreYHZcHUjHMYMIfHfGNYpOdzyA',
    appId: '1:610035185602:ios:faf34b23988df50b5ac85b',
    messagingSenderId: '610035185602',
    projectId: 'yammies-food-app',
    storageBucket: 'yammies-food-app.firebasestorage.app',
    iosBundleId: 'com.example.yummiesFoodApp',
    databaseURL: 'https://yummies-food-app-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9tKQfSreYHZcHUjHMYMIfHfGNYpOdzyA',
    appId: '1:610035185602:ios:faf34b23988df50b5ac85b',
    messagingSenderId: '610035185602',
    projectId: 'yammies-food-app',
    storageBucket: 'yammies-food-app.firebasestorage.app',
    iosBundleId: 'com.example.yummiesFoodApp',
    databaseURL: 'https://yummies-food-app-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqAhD8l7OBt4IS0k5piZaFbFKi6XZggmc',
    appId: '1:610035185602:web:50e10107d0778dad5ac85b',
    messagingSenderId: '610035185602',
    projectId: 'yammies-food-app',
    authDomain: 'yammies-food-app.firebaseapp.com',
    storageBucket: 'yammies-food-app.firebasestorage.app',
    measurementId: 'G-LHK1K81V4M',
    databaseURL: 'https://yummies-food-app-default-rtdb.firebaseio.com',
  );
}
